### ISSUE TITLE
Consider contributing to https://appimage.github.io/

### ISSUE THREAD

**Issue by abvee** [ivan-hc/Chrome-appimage#1]
Hey, your AppImages are excellent and work without flaws. I'm impressed with the browser appimages the most because most of the time they just are not up to spec, but yours are.

Consider contributing [here](https://appimage.github.io/), I'm sure it will be appreciated.

**Comment by ivan-hc** [comment]
Hi, thank you for your appreciation, but about...

> Consider contributing [here](https://appimage.github.io/), I'm sure it will be appreciated.

I've already done 10 PR months ago, the creator of AppImages and owner of the site said in all cases that "I should contrib with main developers to made the Appimages official" and that him "will not upload third-party apps" (while on the website there are third party apps too, and many of them no more exist.

So I already know that my AppImages are not welcome.

Another thing, sometime I have to upload AppImages built on top of Debian Stable, not a recommended system, being it "too new". I have an opposite theory, being updates really important for cyber security, I would recommend people to upgrade their systems. Sometime schools, servers and other businnes-related realities use to keep old Linux systems, so it would be a sacrifice I can accept (until I don't have tools and environments to made them work really everywhere, I'm working on "[ArchImages](https://github.com/ivan-hc/ArchImage)" for this reason).

In brief, I'm not interested to appimage.github.io , it is only a catalogue listing many AppImages old and no more available or developed... also, that has not descriptions, download links (in many cases) and other stuff that can help people to know more about the apps and keep them updated. 

Finally, I've developed my own catalogue that corrects all the things that appimage.github.io and appimagehub.com have not. Here you are a comparison:

- https://www.appimagehub.com 1280 AppImages and counting (many of them old and no more working);
- https://appimage.github.io 1381 AppImages listed (many of them not downloadable, or no more available and dead projects);
- https://portable-linux-apps.github.io 1781 portable apps (of these about 1700 are AppImages, all downloadable and updatable, for real), and this is my website, the only one directly related to my tools (and now by writing "Portable Linux Apps" on Google, this is the first result).

This is why I don't want to wast my time with useless catalogues, I've built one that have a sense, at least.
